spring:
  application:
    name: SHOPPING-SERVICE
  datasource:
    username: root
    password: Santhosh@18
    url: jdbc:mysql://localhost:3306/bookstore
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
server:
  port: 8083
